# Generated by Django 5.1.3 on 2024-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("departure_dt", models.DateTimeField()),
                ("arrival_dt", models.DateTimeField()),
                ("flight_time", models.CharField(max_length=50)),
            ],
        ),
    ]
