# Generated by Django 5.1.3 on 2024-11-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightdetail",
            name="destination",
            field=models.CharField(default="ghj", max_length=100),
            preserve_default=False,
        ),
    ]
